# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in bojko_pulls_github_pulls.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"
gem "aws-sdk-dynamodb"

group :development do
  gem "standard"
end
